/*
 * TestApp.java
 *
 * Created on 22. April 2008, 15:30
 *
 * This file is part of the Java File Copy Library.
 * 
 * The Java File Copy Libraryis free software; you can redistribute it and/or
 * modify it under the terms of the GNU Lesser General Public License as
 * published by the Free Software Foundation; either version 3 of the License,
 * or (at your option) any later version.
 * 
 * The Java File Copy Libraryis distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Lesser General Public License for more details.
 * 
 * You should have received a copy of the GNU Lesser General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */

package ch.fhnw.filecopier;

import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.SwingWorker;

/**
 * A small application for testing the Java File Copy Library.
 * @author Ronny Standtke <Ronny.Standtke@gmx.net>
 */
public class TestApp extends javax.swing.JFrame {

    private final Logger logger = Logger.getLogger(TestApp.class.getName());

    /** Creates new form TestApp */
    public TestApp() {
        initComponents();

        // test run
        final FileCopier fileCopier = new FileCopier();
        fileCopierPanel.setFileCopier(fileCopier);
        SwingWorker copier = new SwingWorker<Void, Void>() {

            @Override
            protected Void doInBackground() {
                try {
                    CopyJob job1 = new CopyJob(true, "/mnt/sda8/ronny",
                            "/media/sda8/archiv/knoppix/KNOPPIX_V5.3.1DVD-2008-03-26-DE.iso");
                    fileCopier.copy(job1, job1);
                } catch (Exception ex) {
                    logger.log(Level.SEVERE, null, ex);
                }
                return null;
            }

            @Override
            protected void done() {
                System.out.println("fertsch!");
            }
        };
        copier.execute();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fileCopierPanel = new ch.fhnw.filecopier.FileCopierPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(fileCopierPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(fileCopierPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            @Override
            public void run() {
                new TestApp().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private ch.fhnw.filecopier.FileCopierPanel fileCopierPanel;
    // End of variables declaration//GEN-END:variables
}
